language: python
python:
  - "2.7"
# requires redis-server for multiprocess tests
services:
  - redis-server
# command to install dependencies
install: 
  - "pip install mockredispy==2.7.5.1 redis==2.4.11"
  - "pip install ."
# command to run tests
script: nosetests

